databases:
  - name: pulsechat-db
    plan: free
    databaseName: chatapp
    user: chat
    ipAllowList: []

services:
  - type: redis
    name: pulsechat-redis
    plan: free
    ipAllowList: []
    maxmemoryPolicy: allkeys-lru

  - type: web
    name: pulsechat
    plan: free
    runtime: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: render
      - key: DB_HOST
        fromDatabase:
          name: pulsechat-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: pulsechat-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: pulsechat-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: pulsechat-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: pulsechat-db
          property: password
      - key: REDIS_URL
        fromService:
          name: pulsechat-redis
          type: redis
          property: connectionString
      - key: APP_SECURITY_MODE
        value: dev
      - key: APP_SECURITY_ALLOW_HEADER_IMPERSONATION
        value: "false"
      - key: APP_MESSAGING_PROVIDER
        value: local
      - key: APP_AI_ENABLED
        value: "false"
